# Generated by Django 4.2.23 on 2025-06-26 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sims.users.models


class Migration(migrations.Migration):

    dependencies = [
        ("rotations", "0002_department_opd_schedule_department_ot_schedule"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupervisorProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"role": "supervisor"},
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="supervisor_profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supervisor_type",
                    models.CharField(
                        choices=[
                            ("fcps", "FCPS"),
                            ("md_ms", "MD/MS"),
                            ("diploma", "Diploma"),
                        ],
                        help_text="Type of supervisor qualification",
                        max_length=20,
                    ),
                ),
                (
                    "cv_file",
                    models.FileField(
                        blank=True,
                        help_text="Curriculum Vitae document",
                        null=True,
                        upload_to=sims.users.models.upload_supervisor_cv,
                    ),
                ),
                (
                    "specialty_certificate_file",
                    models.FileField(
                        blank=True,
                        help_text="Specialty/qualification certificate",
                        null=True,
                        upload_to=sims.users.models.upload_supervisor_certificate,
                    ),
                ),
                (
                    "publications_list_file",
                    models.FileField(
                        blank=True,
                        help_text="List of publications or significant achievements",
                        null=True,
                        upload_to=sims.users.models.upload_supervisor_publications,
                    ),
                ),
                (
                    "cv_verified",
                    models.BooleanField(default=False, help_text="Admin verified CV"),
                ),
                (
                    "specialty_certificate_verified",
                    models.BooleanField(
                        default=False, help_text="Admin verified specialty certificate"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        help_text="Department affiliation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supervisors_in_department",
                        to="rotations.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supervisor Profile",
                "verbose_name_plural": "Supervisor Profiles",
            },
        ),
        migrations.CreateModel(
            name="ResidentProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"role": "pg"},
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="resident_profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "training_type",
                    models.CharField(
                        choices=[
                            ("fcps", "FCPS"),
                            ("md_ms", "MD/MS"),
                            ("diploma", "Diploma"),
                            ("other", "Other"),
                        ],
                        help_text="Type of training program",
                        max_length=20,
                    ),
                ),
                (
                    "program_duration",
                    models.PositiveIntegerField(
                        help_text="Duration of the training program in years"
                    ),
                ),
                (
                    "mbbs_certificate",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=sims.users.models.upload_resident_initial_credential,
                    ),
                ),
                ("mbbs_certificate_verified", models.BooleanField(default=False)),
                (
                    "fsc_certificate",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=sims.users.models.upload_resident_initial_credential,
                    ),
                ),
                ("fsc_certificate_verified", models.BooleanField(default=False)),
                (
                    "matric_certificate",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=sims.users.models.upload_resident_initial_credential,
                    ),
                ),
                ("matric_certificate_verified", models.BooleanField(default=False)),
                (
                    "pmdc_registration",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=sims.users.models.upload_resident_initial_credential,
                    ),
                ),
                ("pmdc_registration_verified", models.BooleanField(default=False)),
                (
                    "house_job_certificate",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=sims.users.models.upload_resident_initial_credential,
                    ),
                ),
                ("house_job_certificate_verified", models.BooleanField(default=False)),
                (
                    "experience_certificate",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=sims.users.models.upload_resident_initial_credential,
                    ),
                ),
                ("experience_certificate_verified", models.BooleanField(default=False)),
                (
                    "program_letter",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=sims.users.models.upload_resident_initial_credential,
                    ),
                ),
                ("program_letter_verified", models.BooleanField(default=False)),
                (
                    "workshop_details_file",
                    models.FileField(
                        blank=True,
                        help_text="Consolidated workshops details or zip",
                        null=True,
                        upload_to=sims.users.models.upload_resident_ongoing_document,
                    ),
                ),
                ("workshop_details_verified", models.BooleanField(default=False)),
                (
                    "imm_result_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=sims.users.models.upload_resident_ongoing_document,
                    ),
                ),
                ("imm_result_verified", models.BooleanField(default=False)),
                (
                    "final_exam_result_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=sims.users.models.upload_resident_ongoing_document,
                    ),
                ),
                ("final_exam_result_verified", models.BooleanField(default=False)),
                (
                    "thesis_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=sims.users.models.upload_resident_ongoing_document,
                    ),
                ),
                ("thesis_verified", models.BooleanField(default=False)),
                (
                    "wpba_records_file",
                    models.FileField(
                        blank=True,
                        help_text="Workplace Based Assessments records",
                        null=True,
                        upload_to=sims.users.models.upload_resident_ongoing_document,
                    ),
                ),
                ("wpba_records_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        help_text="Current primary department (if any)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="residents_in_department",
                        to="rotations.department",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Assigned supervisor",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_residents",
                        to="users.supervisorprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resident Profile",
                "verbose_name_plural": "Resident Profiles",
            },
        ),
    ]
