# Generated by Django 4.2.23 on 2025-06-26 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='opd_schedule',
            field=models.TextField(blank=True, help_text='OPD schedule for the department (e.g., JSON or plain text)'),
        ),
        migrations.AddField(
            model_name='department',
            name='ot_schedule',
            field=models.TextField(blank=True, help_text='OT schedule for the department (e.g., JSON or plain text)'),
        ),
    ]
